---

dist: focal
sudo: required

env:
  - MAVEN_VERSION=3.8.1
  - GRADLE_VERSION=7.0

# Install ansible
addons:
  apt:
    packages:
      - ansible

install:
  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - ./test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
