---

- name: Install dependencies
  ansible.builtin.apt:
    name: unzip
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Fetch gradle
  ansible.builtin.unarchive:
    src: "{{ gradle_download_url }}"
    dest: /opt
    remote_src: true
  become: true

- name: Create gradle symlink
  ansible.builtin.file:
    src: /opt/gradle-{{ gradle_version }}/bin/gradle
    dest: /usr/local/bin/gradle
    state: link
  become: true

- name: Create vanity GRADLE_HOME
  ansible.builtin.file:
    src: /opt/gradle-{{ gradle_version }}
    dest: /opt/gradle
    state: link
    force: true
  become: true
