---

- name: add apt-key
  apt_key:
    id: 6DC3636DAE534049C8B94623A122542AB04F24E3
    url: https://apt.corretto.aws/corretto.key
    state: present
  become: yes

- name: add apt-repo
  apt_repository:
    repo: deb https://apt.corretto.aws stable main
    state: present
  become: yes

- name: install java
  apt:
    name: '{{ oracle_java_package }}'
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: get jname
  shell: set -eo pipefail; dirname "$(dirname "$(dpkg -L '{{ oracle_java_package }}' | grep -e bin/java$ | grep -v jre | head -n1)")"
  changed_when: no
  register: oracle_jname

# unfortunately no way to run error-free by only ignoring browser-plugin
- name: set oracle-jdk back as default
  command: update-java-alternatives --set "{{ oracle_jname.stdout }}"
  become: yes
  ignore_errors: yes
  changed_when: no
