---

- name: Add apt key
  ansible.builtin.get_url:
    url: https://apt.corretto.aws/corretto.key
    dest: /etc/apt/trusted.gpg.d/corretto.asc
    mode: '0644'
  become: true

- name: Add apt-repo
  ansible.builtin.apt_repository:
    repo: deb https://apt.corretto.aws stable main
    state: present
  become: true

- name: Install java
  ansible.builtin.apt:
    name:
      - ca-certificates-java
      - java-1.8.0-amazon-corretto-jdk
      - java-11-amazon-corretto-jdk
      - java-17-amazon-corretto-jdk
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Get jname
  ansible.builtin.shell: set -eo pipefail; dirname "$(dirname "$(dpkg -L '{{ default_java_package }}' | grep -e bin/java$ | grep -v jre | head -n1)")"
  args:
    executable: /bin/bash
  changed_when: false
  register: jname

# unfortunately no way to run error-free by only ignoring browser-plugin
- name: Set default java
  ansible.builtin.command: update-java-alternatives --set "{{ jname.stdout }}"
  become: true
  failed_when: false
  changed_when: false
