---

- name: add apt-key
  apt_key:
    id: 6DC3636DAE534049C8B94623A122542AB04F24E3
    url: https://apt.corretto.aws/corretto.key
    state: present
  become: yes

- name: add apt-repo
  apt_repository:
    repo: deb https://apt.corretto.aws stable main
    state: present
  become: yes

- name: install java
  apt:
    name:
      - java-1.8.0-amazon-corretto-jdk
      - java-11-amazon-corretto-jdk
      - java-17-amazon-corretto-jdk
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: get jname
  shell: set -eo pipefail; dirname "$(dirname "$(dpkg -L '{{ default_java_package }}' | grep -e bin/java$ | grep -v jre | head -n1)")"
  args:
    executable: /bin/bash
  changed_when: no
  register: jname

# unfortunately no way to run error-free by only ignoring browser-plugin
- name: set default java
  command: update-java-alternatives --set "{{ jname.stdout }}"
  become: yes
  ignore_errors: yes
  changed_when: no
