---

- import_tasks: install.yml

- name: check maven version
  command: /opt/apache-maven/bin/mvn --version
  register: maven_current_version
  ignore_errors: yes
  changed_when: no
  when:
    - maven_version is defined
    - maven_version | length > 0

- import_tasks: maven.yml
  when:
    - maven_version is defined
    - maven_version != ''
    - maven_current_version is failed or not maven_current_version.stdout is search(maven_version_string_match)

- name: check gradle version
  command: /opt/gradle/bin/gradle --version
  register: gradle_current_version
  ignore_errors: yes
  changed_when: no
  when:
    - gradle_version is defined
    - gradle_version | length > 0

- import_tasks: gradle.yml
  when:
    - gradle_version is defined
    - gradle_version | length > 0
    - gradle_current_version is failed or not gradle_current_version.stdout is search(gradle_version_string_match)
