---

- import_tasks: install.yml

- name: get jname
  shell: basename "$(dpkg -L {{ oracle_java_package }} | grep -e 'lib/jvm/[^.][^/]\+$')"
  register: oracle_jname

# unfortunately no way to run error-free by only ignoring browser-plugin
- name: set oracle-jdk back as default
  command: update-java-alternatives --set "{{ oracle_jname.stdout }}"
  become: yes
  ignore_errors: yes

- name: check maven version
  command: /opt/apache-maven/bin/mvn --version
  register: maven_current_version
  ignore_errors: yes
  when:
    - maven_version is defined
    - maven_version != ''

- import_tasks: maven.yml
  when:
    - maven_version is defined
    - maven_version != ''
    - maven_current_version is failed or not maven_current_version.stdout is search(maven_version_string_match)

- name: check gradle version
  command: /opt/gradle/bin/gradle --version
  register: gradle_current_version
  ignore_errors: yes
  when:
    - gradle_version is defined
    - gradle_version != ''

- import_tasks: gradle.yml
  when:
    - gradle_version is defined
    - gradle_version != ''
    - gradle_current_version is failed or not gradle_current_version.stdout is search(gradle_version_string_match)
