---

- import_tasks: install.yml

- name: get jname
  shell: dirname "$(dirname "$(dpkg -L '{{ oracle_java_package }}' | grep -e bin/java$ | grep -v jre | head -n1)")"
  changed_when: no
  register: oracle_jname

# unfortunately no way to run error-free by only ignoring browser-plugin
- name: set oracle-jdk back as default
  command: update-java-alternatives --set "{{ oracle_jname.stdout }}"
  become: yes
  ignore_errors: yes
  changed_when: no

- name: check maven version
  command: /opt/apache-maven/bin/mvn --version
  register: maven_current_version
  ignore_errors: yes
  changed_when: no
  when:
    - maven_version is defined
    - maven_version | length > 0

- import_tasks: maven.yml
  when:
    - maven_version is defined
    - maven_version != ''
    - maven_current_version is failed or not maven_current_version.stdout is search(maven_version_string_match)

- name: check gradle version
  command: /opt/gradle/bin/gradle --version
  register: gradle_current_version
  ignore_errors: yes
  changed_when: no
  when:
    - gradle_version is defined
    - gradle_version | length > 0

- import_tasks: gradle.yml
  when:
    - gradle_version is defined
    - gradle_version | length > 0
    - gradle_current_version is failed or not gradle_current_version.stdout is search(gradle_version_string_match)
