---

- name: Install dependencies
  ansible.builtin.apt:
    name: unzip
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Fetch maven
  ansible.builtin.unarchive:
    src: "{{ maven_download_url }}"
    dest: /opt
    remote_src: true
  become: true
  ignore_errors: true
  register: fetch_maven

- name: Create mvn symlink
  ansible.builtin.file:
    src: /opt/apache-maven-{{ maven_version }}/bin/mvn
    dest: /usr/local/bin/mvn
    state: link
  become: true

- name: Create vanity MAVEN_HOME
  ansible.builtin.file:
    src: /opt/apache-maven-{{ maven_version }}
    dest: /opt/apache-maven
    state: link
    force: true
  become: true
