---

- name: install dependencies
  apt:
    name: unzip
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: fetch maven
  unarchive:
    src: "{{ maven_download_url }}"
    dest: /opt
    remote_src: yes
  become: yes

- name: create mvn symlink
  file:
    src: /opt/apache-maven-{{ maven_version }}/bin/mvn
    dest: /usr/local/bin/mvn
    state: link
  become: yes

- name: create vanity MAVEN_HOME
  file:
    src: /opt/apache-maven-{{ maven_version }}
    dest: /opt/apache-maven
    state: link
    force: yes
  become: yes
