version: 2.1

jobs:

  build:
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#machine
      image: ubuntu-2004:202201-02
    environment:
      ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3

    steps:
      - run: sudo rm -f /etc/apt/sources.list.d/google* /etc/apt/sources.list.d/heroku*
      - run: ls -lh /etc/apt/sources.list.d/
      - run: sudo apt remove --assume-yes --purge apparmor
      - run: sudo apt update
      - run: sudo apt install tree

      # prep
      - run: sudo useradd -d /home/mcs -m -s /bin/bash mcs
      - run: sudo -u mcs mkdir -p /home/mcs/.ansible/tmp

      - run: pip3 install ansible ansible-lint

      - run: ansible --version
      - run: ansible-lint --version

      - checkout
      - run: printf '[defaults]\nroles_path=../' > ansible.cfg
      - run: ansible-lint

      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local -v
      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local

      # debug
      - run: /opt/gradle/bin/gradle --version
      - run: /opt/apache-maven/bin/mvn --version
